<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'Plugin\Sample\Event' shared autowired service.

include_once $this->targetDirs[3].'/app/Plugin/Sample/Event.php';

return $this->services['Plugin\\Sample\\Event'] = new \Plugin\Sample\Event(${($_ = isset($this->services['Plugin\\Sample\\Repository\\CustomerRankRepository']) ? $this->services['Plugin\\Sample\\Repository\\CustomerRankRepository'] : $this->load('getCustomerRankRepositoryService.php')) && false ?: '_'});
