<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'Plugin\Sample\Repository\Master\RankRepository' shared autowired service.

include_once $this->targetDirs[3].'/app/Plugin/Sample/Repository/Master/RankRepository.php';

return $this->services['Plugin\\Sample\\Repository\\Master\\RankRepository'] = new \Plugin\Sample\Repository\Master\RankRepository(${($_ = isset($this->services['doctrine']) ? $this->services['doctrine'] : $this->getDoctrineService()) && false ?: '_'});
