<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'Customize\Controller\SamplePageController' shared autowired service.

include_once $this->targetDirs[3].'/app/Customize/Controller/SamplePageController.php';

return $this->services['Customize\\Controller\\SamplePageController'] = new \Customize\Controller\SamplePageController();
