<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'Plugin\Sample\Form\Extension\CustomerTypeExtension' shared autowired service.

include_once $this->targetDirs[3].'/vendor/symfony/form/FormTypeExtensionInterface.php';
include_once $this->targetDirs[3].'/vendor/symfony/form/AbstractTypeExtension.php';
include_once $this->targetDirs[3].'/app/Plugin/Sample/Form/Extension/CustomerTypeExtension.php';

return $this->services['Plugin\\Sample\\Form\\Extension\\CustomerTypeExtension'] = new \Plugin\Sample\Form\Extension\CustomerTypeExtension();
