<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container58fwq0e\EccubeProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container58fwq0e/EccubeProdProjectContainer.php') {
    touch(__DIR__.'/Container58fwq0e.legacy');

    return;
}

if (!\class_exists(EccubeProdProjectContainer::class, false)) {
    \class_alias(\Container58fwq0e\EccubeProdProjectContainer::class, EccubeProdProjectContainer::class, false);
}

return new \Container58fwq0e\EccubeProdProjectContainer([
    'container.build_hash' => '58fwq0e',
    'container.build_id' => 'f9a9176c',
    'container.build_time' => 1592299477,
], __DIR__.\DIRECTORY_SEPARATOR.'Container58fwq0e');
