<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerEpxexog\EccubeDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerEpxexog/EccubeDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerEpxexog.legacy');

    return;
}

if (!\class_exists(EccubeDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerEpxexog\EccubeDevDebugProjectContainer::class, EccubeDevDebugProjectContainer::class, false);
}

return new \ContainerEpxexog\EccubeDevDebugProjectContainer([
    'container.build_hash' => 'Epxexog',
    'container.build_id' => '99f93bae',
    'container.build_time' => 1592983878,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerEpxexog');
